version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    # dockerfile: Dockerfile

  api:
    build: ./api
    command: npm run dev
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.2 # Change to specific version
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo_user
    #   MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - 27017:27017
    volumes:
      # Save persistant data to container mongo_data_container
      - mongo_db_data_container:/data/db
      - node_modules:/app/node_modules

volumes:
  mongo_db_data_container:
  node_modules:


